### ISSUE TITLE
timestamp?

### ISSUE THREAD

**Issue by ardhipoetra** [ardhipoetra/vgridscheduler-python#13]
About fault-tolerance, consistency, and checkpoint, we need to define timestamp in our system that will be synchronized with the other GS.

The question is, what is the good data structure for that?

**Comment by sudeshm** [comment]
I think we can use the lamport clock /vector clock for the synchronisation

http://blog.8thlight.com/rylan-dirksen/2013/10/04/synchronization-in-a-distributed-system.html

**Comment by ardhipoetra** [comment]
I prefer lamport clock, because it seems easier to implement and match better with the VGS. Probably will use the timestamp only for _synchronize_ the state
