### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by sudeshm** [ardhipoetra/vgridscheduler-python#24]
![image](https://cloud.githubusercontent.com/assets/8092165/6720296/ff40f158-cdc1-11e4-8657-bb72c01e96bd.png)

I see some issues with the starting .. have u notice that job notification do not come for all the jobs submitted ?

is this the right  behaviour ? first three options ? why should we open the internal information to the end user ?  like cluster information ? might be sensitive in real life scenario?

**Comment by ardhipoetra** [comment]
if you see at the code, it is indeed 0, 1, 2, and 3 'keyword' are reserved for doing something. Other than that, it is assumed as 'jobs'

well, this is just for debugging, we can modify those stuff later on. For now, just open everything. We want to understand our own program behaviour, right? ;)
