### ISSUE TITLE
RM object id 

### ISSUE THREAD

**Issue by sudeshm** [ardhipoetra/vgridscheduler-python#26]
if len(sys.argv) == 0:
        oid = len(ns.list(prefix=Constant.NAMESPACE_RM+"."))
    else:
        oid = int(sys.argv[1])

```
oid = len(ns.list(prefix=Constant.NAMESPACE_RM+"."))

node = ResourceManager(oid, "[RM-"+str(oid)+"]", Constant.TOTAL_NODE_EACH)
```

Result --->>>

Input:gs [GS-0] created with id 0
gs [GS-1] created with id 1
rm [RM-4] created with id 4
rm [RM-4] created with id 4
rm [RM-5] created with id 5

isnt it strage that RM has same object id ?  however it starts the five process for the RM properly.

**Comment by ardhipoetra** [comment]
I don't get your point. Did you change something in the code?

In default, with RM = 3 and GS = 2, the output should something like : 

```
gs [GS-1] created with id 1
rm [RM-0] created with id 0
rm [RM-1] created with id 1
gs [GS-0] created with id 0
rm [RM-2] created with id 2
```

**Comment by sudeshm** [comment]
No I did not change code in this part  ..... when invoking the new object you are passing Constant.TOTAL_NODE_EACH with value 4 everytime  ? I did not understand why

**Comment by ardhipoetra** [comment]
That just means that for every RM, we have 4 worker node. So let say there are 3 RMs, the total worker node in the system will be 4*3 = 12
