### ISSUE TITLE
Name server

### ISSUE THREAD

**Issue by sudeshm** [ardhipoetra/vgridscheduler-python#28]
If one of the RM goes down Name server will remove its name from the name server list ? I am  not sure

if it does we do not need to monitor the RMs periodically .

**Comment by ardhipoetra** [comment]
yes, and no.

Well, it depends on how we define **down**. If we make it down by removing its name in NS, so be it.

I think we still need to periodically check RM from GS, so GS can 'act' if there's something with RM. GS check it by looking at the name server. How GS know RM is down if it not check periodically?

**Comment by sudeshm** [comment]
after we do the ns = Pyro4.locateNS() it will gives the available name servers ? If the RM is down that URI will not be avilable on this list ?

**Comment by ardhipoetra** [comment]
yes, if we assume RM down = deleted its name server on the list. We have to do this manually, though. In default, if we just stop the RM, the name still in the list
