### ISSUE TITLE
Latest Commit 

### ISSUE THREAD

**Issue by sudeshm** [ardhipoetra/vgridscheduler-python#29]
Added the definition for the v

_monitorRM
get_gs_neighbour_status
get_gs_neighbour_status

few variables such as  neighbor_state gs_URI
.
removed _update_jobdetailsRM

updated the addjob api to send the URI

code is available on the sulabh branch 

once every deoendant functionality is available and full tested will integrate to main branch 

Two imp function are pendin now from GS for consistency  i.e. 
update_GSstructur
and _push_structure

I think we should have separate object for this structure/varible definition ? are you working on the consistency part ?

**Comment by ardhipoetra** [comment]
Yep, for 79a78a0aa631e03c163c22b4690edabd81580488 I already put some consistency part. You can try the code that it will be sync between each other node
