### ISSUE TITLE
Multiple host

### ISSUE THREAD

**Issue by sudeshm** [ardhipoetra/vgridscheduler-python#31]
Here you can find the example to run over multiple machines.

https://pythonhosted.org/Pyro4/servercode.html

![image](https://cloud.githubusercontent.com/assets/8092165/6770974/28cc3782-d0d1-11e4-95b1-40e2ee23f9d6.png)

**Comment by ardhipoetra** [comment]
![gifs](http://gifs.rogierslag.nl/support/Sean-Connery-Fist-Pump-US-Open.gif)

**Comment by ardhipoetra** [comment]
Btw, I will work on multi-host tomorrow in the campus area. Using VPN is too slow :(

**Comment by ardhipoetra** [comment]
note to myself : 
- start name server (preferable in only single place, wherever it may be) : `python -m Pyro4.naming --host=[put IP here]`
- to use nsc : `python -m Pyro4.nsc -n [IP here] [command, e.g "list"]`

in the code as registrar, you have to change the code into (notice the double-quote): 

```
daemon=Pyro4.Daemon("[IP addr]")   
ns=Pyro4.locateNS(host="[IP addr]")  
```

when looking up (for nameserver), you have to provide the host in the `locateNS`. Or if already got an URI, we don't need that anymore. Example : `Pyro4.Proxy("PYRONAME:uri.will.be.here")`

need to discuss how we will implement this stuff into the main program
