### ISSUE TITLE
I pushed the function definition with data details 

### ISSUE THREAD

**Issue by sudeshm** [ardhipoetra/vgridscheduler-python#7]
it should cover maximum what we need for the consistency and replication also it will contain many function that we need for the fault tolerance

**Comment by ardhipoetra** [comment]
I will leave comment here about your recent commits. Probably it will be better if we discuss the needs of our project using this 'issue' instead commenting on source code :/

_main.py_

```
We should ask for the priority of the job here and higher priority jobs go first in the cluster
```

So, you mean that, the job itself can be prioritized? Isn't that gonna be complicated? 

_resourcemanager.py_
1. update_distributedGS : so the output should be the "state" of RM and nodes, right?
2. rmQueue : I will change the function name, it's not really obvious
3. getJobFromRMQueue : Change function name to python-like

_utils.py_

```
#deamon should be started with the seperate host IP and port address
## which IP address should be taken and how ?
```

yeah, good question. Hmm I think for now we can do that locally, but it is indeed important if we want to scale our program.

```
# Should be started as a seperate process separaate memory
```

Isn't thread good enough? Or do we need to use [subprocess](https://docs.python.org/2/library/subprocess.html)?

_gridscheduler.py_

A lot of stuff, let's discuss it : 
- data structure in each GS 

```
may be a new class to club all these stuff together ? or within the same ???
```

I don't think we need it. Just make sure the **state** format is the same. And yeah, it should contain RM and cluster info, including job id/status/tracking status.
- update_jobdetailsRM : so, is it asynchronous? Or synchronous? It's like we're propagating the job, is that right?
- update_GSstructure : what's the right time to call this function? It don't return anything, it seems
- sendDgsDetailsToMasterGS : do we have master GS? What is master GS?
- sendJobDetailsToDistributedGS : Yes, it is indeed we have to inform other GS as well to make sure it's consistent
- maintain_jobqueue

```
# activity :Maintain the job queue in case all the Distributed GS are occupiedd
#output nothing 
```

What do you mean by _maintain_? I don't really understand this function. Or do you mean _inserting_ the job?

other function in this file is clear enough, yay!
